<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
<script type="text/javascript" src="/js/lightbox.min.js"></script>
<script type="text/javascript" src="/js/wow.min.js"></script>
<script type="text/javascript" src="/js/main.js"></script>  
<script type="text/javascript" src="/js/marquee.js"></script>  
<script type="text/javascript" src="/js/scroll.js"></script>  
<script type="text/javascript" src="/js/modernizr.js"></script>
<script type="text/javascript" src="/js/schedule.js"></script>